apiVersion: v1
kind: Service
metadata:
  name: rate-limiting-api
spec:
  ports:
  - port: 8081
    name: http
  type: LoadBalancer
  selector:
    app: rate-limiting-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiting-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rate-limiting-api
  template:
    metadata:
      labels:
        app: rate-limiting-api
    spec:
      containers:
      - name: rate-limiting-api
        image: rate-limiting-api-image
        env:
          - name: AZURE_LOG_LEVEL
            value: "ERROR"
        ports:
          - containerPort: 8081
