spring:
    application:
        name: spring-prometheus-demo
    config:
        activate:
            on-profile: sample

server:
    port : 8082

rateLimitingServiceUrl: ${RATE_LIMITING_SERVICE_URL}

servicebus:
    connectionString: ${SERVICE_BUS_CONNECTION_STRING}
    topicName: ${SERVICE_BUS_TOPIC_NAME}
    subscriptionName: ${SERVICE_BUS_SUBSCRIPTION_NAME}

redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health, metrics, shutdown, prometheus, loggers
#   metrics:
#     tags:
#       application: ${spring.application.name}
#     export:
#       prometheus:
#         enabled: true # Enable Prometheus metrics export