apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: handler-service-prometheus-monitor
spec:
  selector:
    matchLabels:
      app: handler-service
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"